const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

/**
 * Written by hand rather than generated.
 *
 * `expo lint` will install ESLint and write this file itself — silently, without
 * prompting, in a non-interactive shell. That made `pnpm lint` a command that
 * modified the repo as a side effect of being run, so the script now calls
 * `eslint` directly and this config is checked in.
 *
 * The hooks rules matter here specifically: `app.json` sets
 * `experiments.reactCompiler`, and src/app/_layout.tsx depends on a
 * hooks-above-the-early-return invariant that was enforced by nothing but a
 * comment.
 */
module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'dist/*',
      'drizzle/*',
      'android/*',
      'ios/*',
      '.expo/*',
      // Generated by uniwind; checked in, but not ours to lint.
      'src/uniwind-types.d.ts',
    ],
  },
  {
    rules: {
      /*
       * eslint-config-expo already registers the react-hooks plugin — including
       * the React Compiler rules, which live under individual names rather than
       * a single `react-compiler` one. They are enabled here by name because
       * spreading the plugin's own config on top makes ESLint refuse to start
       * with "Cannot redefine plugin".
       *
       * rules-of-hooks is an error rather than a warning on purpose: it is the
       * exact invariant that broke four detail routes in M1, where a hook sat
       * below an early return that only started flipping once the lookup became
       * a query.
       */
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      /*
       * The React Compiler rules advise rather than block. Several of them flag
       * patterns that are deliberate and correct here: the latest-ref idiom in
       * db/live.ts and db/use-action.ts, the documented adjust-state-during-
       * render escape hatch that keeps a query's answer in step with its key,
       * and one-time state synchronisation from the boot sequence. Left as
       * errors they would force those to be rewritten into something worse, so
       * they warn — and the warnings are read, not ignored: two of them were
       * real and are fixed in this change.
       */
      'react-hooks/refs': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/immutability': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/set-state-in-render': 'warn',

      /*
       * eslint-config-expo already enables the TypeScript-aware version of this,
       * which understands type-only imports; the base rule double-reports and
       * gets them wrong, so it stays off.
       */
      'no-unused-vars': 'off',
    },
  },
]);
