#!/usr/bin/env node
/**
 * Builds an Android artifact into builds/.
 *
 * Gradle writes into android/app/build/outputs/, but android/ is generated by
 * prebuild and gitignored — anything left there disappears on the next
 * `pnpm expo prebuild --clean`. This copies the artifact somewhere stable and
 * names it from app.json, so builds/ is the one place to look for a binary.
 *
 * Run: pnpm build:dev | pnpm build:aab
 */

import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ANDROID_DIR = join(ROOT, 'android');

const MODES = {
  dev: {
    describe: 'debug APK with expo-dev-client',
    task: 'assembleDebug',
    artifact: 'app/build/outputs/apk/debug/app-debug.apk',
    outputDir: 'builds/dev',
    filename: (slug, version) => `${slug}-dev-${version}.apk`,
    next: 'pnpm install:dev   # then pnpm start',
  },
  aab: {
    describe: 'release AAB',
    task: 'bundleRelease',
    artifact: 'app/build/outputs/bundle/release/app-release.aab',
    outputDir: 'builds/release',
    filename: (slug, version) => `${slug}-${version}.aab`,
    next: 'upload the .aab to Play Console',
  },
};

function fail(message, hint) {
  console.error(message);
  if (hint) console.error(`  → ${hint}`);
  process.exit(1);
}

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, stdio: 'inherit' });
  if (result.error) fail(`Could not run ${command}: ${result.error.message}`);
  if (result.status !== 0) fail(`${command} ${args.join(' ')} failed.`);
}

const mode = MODES[process.argv[2]];
if (!mode) {
  fail(`Unknown build mode "${process.argv[2] ?? ''}".`, 'expected: dev | aab');
}

/** A missing SDK otherwise surfaces as a Gradle stack trace fifty lines deep. */
const sdkRoot = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
if (!sdkRoot || !existsSync(sdkRoot)) {
  fail(
    'No Android SDK found (ANDROID_HOME / ANDROID_SDK_ROOT is unset or points nowhere).',
    'install the SDK, then export ANDROID_HOME=$HOME/Android/Sdk',
  );
}
if (spawnSync('java', ['-version'], { stdio: 'ignore' }).error) {
  fail('No java on PATH.', 'install a JDK 17+ — Gradle needs it');
}

/**
 * Only generate the native project when it is absent. Regenerating on every
 * build would silently discard native edits; AGENTS.md makes `--clean` a
 * deliberate step after a native dependency or app.json plugin change.
 */
if (!existsSync(ANDROID_DIR)) {
  console.log('No android/ yet — running prebuild.\n');
  run('pnpm', ['expo', 'prebuild', '--platform', 'android'], ROOT);
}

const app = JSON.parse(readFileSync(join(ROOT, 'app.json'), 'utf8')).expo;

console.log(`Building ${mode.describe} for ${app.slug} ${app.version}.\n`);
run('./gradlew', [mode.task], ANDROID_DIR);

const built = join(ANDROID_DIR, mode.artifact);
if (!existsSync(built)) {
  fail(`Gradle reported success but ${mode.artifact} is missing.`);
}

const outputDir = join(ROOT, mode.outputDir);
mkdirSync(outputDir, { recursive: true });

const destination = join(outputDir, mode.filename(app.slug, app.version));
copyFileSync(built, destination);

const megabytes = (statSync(destination).size / 1024 / 1024).toFixed(1);
console.log(`\n${mode.outputDir}/${mode.filename(app.slug, app.version)}  (${megabytes} MB)`);
console.log(`  → ${mode.next}`);

/**
 * Stock prebuild signs release with the debug keystore, which Play rejects.
 * Warn rather than fail: a debug-signed .aab is still useful for internal
 * sharing, and wiring a real keystore is a separate piece of work.
 */
if (mode.task === 'bundleRelease') {
  const gradle = readFileSync(join(ANDROID_DIR, 'app/build.gradle'), 'utf8');
  const releaseBlock = gradle.slice(gradle.indexOf('release {', gradle.indexOf('buildTypes')));
  if (releaseBlock.match(/signingConfig\s+signingConfigs\.(\w+)/)?.[1] === 'debug') {
    console.warn('\nWarning: this bundle is signed with the debug keystore.');
    console.warn('  → Play Console will reject it until a real keystore is wired up.');
  }
}
